version : 2

sources:
  - name: data
    schema: gz_raw_data
    tables:
        - name: sales
          identifier: raw_gz_sales
          description: Sales of Greenweez
        - name: product
          identifier: raw_gz_product
          description : product of Greenweez
        - name: ship
          identifier: raw_gz_ship





