version : 2

sources:
  - name: data
    schema: gz_raw_data
    tables:
        - name: sales
          identifier: raw_gz_sales
          description: Sales of Greenweez
        - name: product
          identifier: raw_gz_product
          description : product of Greenweez
          columns:
            - name: products_id
              description: primary key
              tests:
              - unique
              - not_null    
        - name: ship
          identifier: raw_gz_ship
          description : ship of Greenweez
          columns:
            - name: orders_id
              description : primary key
              tests:
              - unique
              - not_null
        - name: adwords
          identifier: raw_gz_adwords
        - name: bing
          identifier: raw_gz_bing
        - name: criteo
          identifier: raw_gz_criteo
        - name: facebook
          identifier: raw_gz_facebook

models:
  - name: stg_data__sales
    tests:
      - unique:
          column_name: "(products_id||'-'||orders_id)"
      - not_null
      